eureka:
  client: 
    register-with-eureka: true
    fetch-registry: true
   # serviceUrl: 
   #   defaultZone: http://localhost:8010/eureka/
server:
  port: ${PORT:${SERVER_PORT:0}}
words: ran,knew,had,saw,bought

      